-- Migration: Brand Knowledge Base & Strategic Insights
-- Date: 2026-04-12
-- Description: Creates the brand knowledge fact system for verified brand information
--              and strategic_insights table for LLM-generated deep analysis results.

BEGIN;

-- ============================================================================
-- 1. BRAND KNOWLEDGE FACTS — Curated, verified facts about a brand
-- ============================================================================
-- Categories: identity, contact, pricing, products, team, locations, claims,
--             competitors, differentiators, audience
-- Each fact is a key-value pair with provenance and verification metadata.

CREATE TABLE IF NOT EXISTS public.brand_knowledge_facts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  brand_id uuid NOT NULL REFERENCES public.brands(id) ON DELETE CASCADE,
  account_id uuid NOT NULL REFERENCES public.accounts(id) ON DELETE CASCADE,

  -- Fact data
  category varchar(50) NOT NULL,  -- identity, contact, pricing, products, team, locations, claims, competitors, differentiators, audience
  fact_key varchar(200) NOT NULL,  -- e.g. "headquarters", "pricing_starter_plan", "founded_year"
  fact_value text NOT NULL,        -- the verified value
  fact_context text,               -- optional additional context

  -- Provenance
  source varchar(50) NOT NULL DEFAULT 'manual',  -- manual, website_crawl, llm_extracted, api_import
  source_url text,                 -- URL where fact was found
  confidence numeric(3,2) NOT NULL DEFAULT 1.00,  -- 0.00–1.00

  -- Verification
  verified boolean NOT NULL DEFAULT false,
  verified_at timestamptz,
  verified_by uuid,  -- user who verified

  -- Timestamps
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  UNIQUE (brand_id, category, fact_key)
);

CREATE INDEX idx_bkf_brand ON public.brand_knowledge_facts (brand_id);
CREATE INDEX idx_bkf_category ON public.brand_knowledge_facts (brand_id, category);
CREATE INDEX idx_bkf_account ON public.brand_knowledge_facts (account_id);

-- RLS
ALTER TABLE public.brand_knowledge_facts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read brand_knowledge_facts for their accounts"
  ON public.brand_knowledge_facts FOR SELECT USING (
    account_id IN (
      SELECT au.account_id FROM public.account_users au
      WHERE au.user_id = auth.uid() AND au.is_active = true
    )
  );

CREATE POLICY "Users can manage brand_knowledge_facts for their accounts"
  ON public.brand_knowledge_facts FOR ALL USING (
    account_id IN (
      SELECT au.account_id FROM public.account_users au
      WHERE au.user_id = auth.uid() AND au.is_active = true
    )
  );

CREATE POLICY "Service role full access to brand_knowledge_facts"
  ON public.brand_knowledge_facts FOR ALL
  USING (auth.role() = 'service_role');


-- ============================================================================
-- 2. STRATEGIC INSIGHTS — LLM-generated deep analysis results
-- ============================================================================
-- Generated by the strategic insight agent, cached per brand per run.
-- Each row = one complete analysis session.

CREATE TABLE IF NOT EXISTS public.strategic_insights (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  brand_id uuid NOT NULL REFERENCES public.brands(id) ON DELETE CASCADE,
  account_id uuid NOT NULL REFERENCES public.accounts(id) ON DELETE CASCADE,

  -- Generation metadata
  model_used varchar(100) NOT NULL,
  generation_type varchar(50) NOT NULL DEFAULT 'full_analysis',  -- full_analysis, trend_update, competitive_alert, fact_check
  trigger_source varchar(50) NOT NULL DEFAULT 'manual',  -- manual, scheduled, post_run, on_demand

  -- The analysis output
  analysis jsonb NOT NULL DEFAULT '{}',
  -- Structure:
  -- {
  --   executive_summary: string,
  --   key_findings: [{ title, description, severity, category, evidence, recommendation }],
  --   opportunities: [{ title, description, impact, effort, expected_outcome, target_queries }],
  --   threats: [{ title, description, severity, affected_area, mitigation }],
  --   content_strategy: [{ title, target_topic, content_type, target_publications, rationale, priority }],
  --   fact_verification: [{ claim, source, verdict, evidence, correction }],
  --   competitive_intelligence: [{ competitor, insight, implication, action }],
  --   trend_signals: [{ signal, direction, confidence, timeframe, implication }]
  -- }

  -- Data sources used
  data_sources jsonb NOT NULL DEFAULT '{}',
  -- { visibility: bool, discoverability: bool, gsc: bool, knowledge_base: bool, response_count: int }

  -- Scores
  confidence_score numeric(3,2) NOT NULL DEFAULT 0.80,
  data_freshness_hours integer,  -- how old the newest data was

  -- Token usage / cost
  prompt_tokens integer,
  completion_tokens integer,
  cost_usd numeric(8,4),

  -- Timestamps
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz  -- optional TTL for cache invalidation
);

CREATE INDEX idx_si_brand ON public.strategic_insights (brand_id, created_at DESC);
CREATE INDEX idx_si_account ON public.strategic_insights (account_id);
CREATE INDEX idx_si_type ON public.strategic_insights (generation_type);

-- RLS
ALTER TABLE public.strategic_insights ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read strategic_insights for their accounts"
  ON public.strategic_insights FOR SELECT USING (
    account_id IN (
      SELECT au.account_id FROM public.account_users au
      WHERE au.user_id = auth.uid() AND au.is_active = true
    )
  );

CREATE POLICY "Service role full access to strategic_insights"
  ON public.strategic_insights FOR ALL
  USING (auth.role() = 'service_role');


-- ============================================================================
-- 3. Updated_at trigger
-- ============================================================================

CREATE OR REPLACE FUNCTION update_brand_knowledge_facts_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_brand_knowledge_facts_updated_at
  BEFORE UPDATE ON public.brand_knowledge_facts
  FOR EACH ROW EXECUTE FUNCTION update_brand_knowledge_facts_updated_at();

COMMIT;
