/**
 * Onboarding Constants
 * 
 * Brand categories and other constant data used in onboarding
 */

import type { BrandCategory } from './types'

export const BRAND_CATEGORIES: BrandCategory[] = [
  // 🏢 Business & Professional Services
  { value: "accounting", label: "Accounting", group: "Business & Professional Services" },
  { value: "alternative_dispute_resolution", label: "Alternative Dispute Resolution", group: "Business & Professional Services" },
  { value: "animation", label: "Animation", group: "Business & Professional Services" },
  { value: "architecture_planning", label: "Architecture & Planning", group: "Business & Professional Services" },
  { value: "business_supplies_equipment", label: "Business Supplies & Equipment", group: "Business & Professional Services" },
  { value: "commercial_real_estate", label: "Commercial Real Estate", group: "Business & Professional Services" },
  { value: "consulting_management", label: "Consulting (Management)", group: "Business & Professional Services" },
  { value: "environmental_services", label: "Environmental Services", group: "Business & Professional Services" },
  { value: "events_services", label: "Events Services", group: "Business & Professional Services" },
  { value: "executive_office", label: "Executive Office", group: "Business & Professional Services" },
  { value: "facilities_services", label: "Facilities Services", group: "Business & Professional Services" },
  { value: "graphic_design", label: "Graphic Design", group: "Business & Professional Services" },
  { value: "human_resources", label: "Human Resources", group: "Business & Professional Services" },
  { value: "import_export", label: "Import & Export", group: "Business & Professional Services" },
  { value: "information_services", label: "Information Services", group: "Business & Professional Services" },
  { value: "insurance", label: "Insurance", group: "Business & Professional Services" },
  { value: "international_trade_development", label: "International Trade & Development", group: "Business & Professional Services" },
  { value: "law_practice", label: "Law Practice", group: "Business & Professional Services" },
  { value: "legal_services", label: "Legal Services", group: "Business & Professional Services" },
  { value: "logistics_supply_chain", label: "Logistics & Supply Chain", group: "Business & Professional Services" },
  { value: "marketing_advertising", label: "Marketing & Advertising", group: "Business & Professional Services" },
  { value: "market_research", label: "Market Research", group: "Business & Professional Services" },
  { value: "outsourcing_offshoring", label: "Outsourcing/Offshoring", group: "Business & Professional Services" },
  { value: "printing", label: "Printing", group: "Business & Professional Services" },
  { value: "professional_training_coaching", label: "Professional Training & Coaching", group: "Business & Professional Services" },
  { value: "security_investigations", label: "Security & Investigations", group: "Business & Professional Services" },
  { value: "staffing_recruiting", label: "Staffing & Recruiting", group: "Business & Professional Services" },
  { value: "translation_localization", label: "Translation & Localization", group: "Business & Professional Services" },
  { value: "utilities", label: "Utilities", group: "Business & Professional Services" },
  { value: "warehousing", label: "Warehousing", group: "Business & Professional Services" },
  { value: "writing_editing", label: "Writing & Editing", group: "Business & Professional Services" },

  // 💻 Technology, Information & Media
  { value: "computer_games", label: "Computer Games", group: "Technology, Information & Media" },
  { value: "computer_hardware", label: "Computer Hardware", group: "Technology, Information & Media" },
  { value: "computer_networking", label: "Computer Networking", group: "Technology, Information & Media" },
  { value: "computer_software", label: "Computer Software", group: "Technology, Information & Media" },
  { value: "e_learning", label: "E-Learning", group: "Technology, Information & Media" },
  { value: "information_technology_services", label: "Information Technology & Services", group: "Technology, Information & Media" },
  { value: "internet", label: "Internet", group: "Technology, Information & Media" },
  { value: "media_production", label: "Media Production", group: "Technology, Information & Media" },
  { value: "motion_pictures_film", label: "Motion Pictures & Film", group: "Technology, Information & Media" },
  { value: "nanotechnology", label: "Nanotechnology", group: "Technology, Information & Media" },
  { value: "online_media", label: "Online Media", group: "Technology, Information & Media" },
  { value: "semiconductors", label: "Semiconductors", group: "Technology, Information & Media" },
  { value: "telecommunications", label: "Telecommunications", group: "Technology, Information & Media" },
  { value: "wireless", label: "Wireless", group: "Technology, Information & Media" },

  // 🛒 Consumer Goods & Retail
  { value: "apparel_fashion", label: "Apparel & Fashion", group: "Consumer Goods & Retail" },
  { value: "arts_crafts", label: "Arts & Crafts", group: "Consumer Goods & Retail" },
  { value: "automotive", label: "Automotive", group: "Consumer Goods & Retail" },
  { value: "beauty", label: "Beauty", group: "Consumer Goods & Retail" },
  { value: "consumer_electronics", label: "Consumer Electronics", group: "Consumer Goods & Retail" },
  { value: "consumer_goods", label: "Consumer Goods", group: "Consumer Goods & Retail" },
  { value: "cosmetics", label: "Cosmetics", group: "Consumer Goods & Retail" },
  { value: "food_beverages", label: "Food & Beverages", group: "Consumer Goods & Retail" },
  { value: "food_production", label: "Food Production", group: "Consumer Goods & Retail" },
  { value: "furniture", label: "Furniture", group: "Consumer Goods & Retail" },
  { value: "grocery", label: "Grocery", group: "Consumer Goods & Retail" },
  { value: "home_goods", label: "Home Goods", group: "Consumer Goods & Retail" },
  { value: "luxury_goods_jewelry", label: "Luxury Goods & Jewelry", group: "Consumer Goods & Retail" },
  { value: "retail", label: "Retail", group: "Consumer Goods & Retail" },
  { value: "sporting_goods", label: "Sporting Goods", group: "Consumer Goods & Retail" },
  { value: "supermarkets", label: "Supermarkets", group: "Consumer Goods & Retail" },
  { value: "tobacco", label: "Tobacco", group: "Consumer Goods & Retail" },
  { value: "toys", label: "Toys", group: "Consumer Goods & Retail" },
  { value: "wine_spirits", label: "Wine & Spirits", group: "Consumer Goods & Retail" },

  // 🏥 Health, Wellness & Life Sciences
  { value: "alternative_medicine", label: "Alternative Medicine", group: "Health, Wellness & Life Sciences" },
  { value: "biotechnology", label: "Biotechnology", group: "Health, Wellness & Life Sciences" },
  { value: "health_wellness_fitness", label: "Health, Wellness & Fitness", group: "Health, Wellness & Life Sciences" },
  { value: "hospital_health_care", label: "Hospital & Health Care", group: "Health, Wellness & Life Sciences" },
  { value: "medical_devices", label: "Medical Devices", group: "Health, Wellness & Life Sciences" },
  { value: "medical_practice", label: "Medical Practice", group: "Health, Wellness & Life Sciences" },
  { value: "mental_health_care", label: "Mental Health Care", group: "Health, Wellness & Life Sciences" },
  { value: "pharmaceuticals", label: "Pharmaceuticals", group: "Health, Wellness & Life Sciences" },
  { value: "research", label: "Research", group: "Health, Wellness & Life Sciences" },
  { value: "veterinary", label: "Veterinary", group: "Health, Wellness & Life Sciences" },

  // 💰 Finance & Real Estate
  { value: "banking", label: "Banking", group: "Finance & Real Estate" },
  { value: "capital_markets", label: "Capital Markets", group: "Finance & Real Estate" },
  { value: "financial_services", label: "Financial Services", group: "Finance & Real Estate" },
  { value: "investment_banking", label: "Investment Banking", group: "Finance & Real Estate" },
  { value: "investment_management", label: "Investment Management", group: "Finance & Real Estate" },
  { value: "real_estate_residential", label: "Real Estate (Residential)", group: "Finance & Real Estate" },
  { value: "venture_capital_private_equity", label: "Venture Capital & Private Equity", group: "Finance & Real Estate" },

  // 🏭 Manufacturing & Industrials
  { value: "airlines_aviation", label: "Airlines/Aviation", group: "Manufacturing & Industrials" },
  { value: "aviation_aerospace", label: "Aviation & Aerospace", group: "Manufacturing & Industrials" },
  { value: "building_materials", label: "Building Materials", group: "Manufacturing & Industrials" },
  { value: "chemicals", label: "Chemicals", group: "Manufacturing & Industrials" },
  { value: "civil_engineering", label: "Civil Engineering", group: "Manufacturing & Industrials" },
  { value: "construction", label: "Construction", group: "Manufacturing & Industrials" },
  { value: "defense_space", label: "Defense & Space", group: "Manufacturing & Industrials" },
  { value: "electrical_electronic_manufacturing", label: "Electrical/Electronic Manufacturing", group: "Manufacturing & Industrials" },
  { value: "farming", label: "Farming", group: "Manufacturing & Industrials" },
  { value: "fishery", label: "Fishery", group: "Manufacturing & Industrials" },
  { value: "glass_ceramics_concrete", label: "Glass, Ceramics & Concrete", group: "Manufacturing & Industrials" },
  { value: "industrial_automation", label: "Industrial Automation", group: "Manufacturing & Industrials" },
  { value: "machinery", label: "Machinery", group: "Manufacturing & Industrials" },
  { value: "maritime", label: "Maritime", group: "Manufacturing & Industrials" },
  { value: "mechanical_industrial_engineering", label: "Mechanical or Industrial Engineering", group: "Manufacturing & Industrials" },
  { value: "mining_metals", label: "Mining & Metals", group: "Manufacturing & Industrials" },
  { value: "oil_energy", label: "Oil & Energy", group: "Manufacturing & Industrials" },
  { value: "package_freight_delivery", label: "Package/Freight Delivery", group: "Manufacturing & Industrials" },
  { value: "packaging_containers", label: "Packaging & Containers", group: "Manufacturing & Industrials" },
  { value: "paper_forest_products", label: "Paper & Forest Products", group: "Manufacturing & Industrials" },
  { value: "plastics", label: "Plastics", group: "Manufacturing & Industrials" },
  { value: "renewables_environment", label: "Renewables & Environment", group: "Manufacturing & Industrials" },
  { value: "shipbuilding", label: "Shipbuilding", group: "Manufacturing & Industrials" },
  { value: "textiles", label: "Textiles", group: "Manufacturing & Industrials" },
  { value: "transportation_trucking_railroad", label: "Transportation/Trucking/Railroad", group: "Manufacturing & Industrials" },

  // 🧑‍🏫 Services: Consumer & Public
  { value: "accommodation", label: "Accommodation", group: "Services: Consumer & Public" },
  { value: "airlines", label: "Airlines", group: "Services: Consumer & Public" },
  { value: "civic_social_organization", label: "Civic & Social Organization", group: "Services: Consumer & Public" },
  { value: "education_management", label: "Education Management", group: "Services: Consumer & Public" },
  { value: "entertainment", label: "Entertainment", group: "Services: Consumer & Public" },
  { value: "government_administration", label: "Government Administration", group: "Services: Consumer & Public" },
  { value: "government_relations", label: "Government Relations", group: "Services: Consumer & Public" },
  { value: "higher_education", label: "Higher Education", group: "Services: Consumer & Public" },
  { value: "hospitality", label: "Hospitality", group: "Services: Consumer & Public" },
  { value: "individual_family_services", label: "Individual & Family Services", group: "Services: Consumer & Public" },
  { value: "leisure_travel_tourism", label: "Leisure, Travel & Tourism", group: "Services: Consumer & Public" },
  { value: "libraries", label: "Libraries", group: "Services: Consumer & Public" },
  { value: "museums_institutions", label: "Museums & Institutions", group: "Services: Consumer & Public" },
  { value: "music", label: "Music", group: "Services: Consumer & Public" },
  { value: "newspapers", label: "Newspapers", group: "Services: Consumer & Public" },
  { value: "non_profit_organization_management", label: "Non-Profit Organization Management", group: "Services: Consumer & Public" },
  { value: "performing_arts", label: "Performing Arts", group: "Services: Consumer & Public" },
  { value: "primary_secondary_education", label: "Primary/Secondary Education", group: "Services: Consumer & Public" },
  { value: "public_policy", label: "Public Policy", group: "Services: Consumer & Public" },
  { value: "public_relations_communications", label: "Public Relations & Communications", group: "Services: Consumer & Public" },
  { value: "public_safety", label: "Public Safety", group: "Services: Consumer & Public" },
  { value: "recreational_facilities_services", label: "Recreational Facilities & Services", group: "Services: Consumer & Public" },
  { value: "religious_institutions", label: "Religious Institutions", group: "Services: Consumer & Public" },
  { value: "restaurants", label: "Restaurants", group: "Services: Consumer & Public" },
  { value: "sports", label: "Sports", group: "Services: Consumer & Public" },

  // � Startups & Internet Business
  { value: "saas", label: "SaaS (Software as a Service)", group: "Startups & Internet Business" },
  { value: "fintech", label: "Fintech", group: "Startups & Internet Business" },
  { value: "ecommerce_platform", label: "E-commerce Platform", group: "Startups & Internet Business" },
  { value: "marketplace", label: "Marketplace", group: "Startups & Internet Business" },
  { value: "mobile_apps", label: "Mobile Apps", group: "Startups & Internet Business" },
  { value: "web_apps", label: "Web Apps", group: "Startups & Internet Business" },
  { value: "api_services", label: "API Services", group: "Startups & Internet Business" },
  { value: "cloud_services", label: "Cloud Services", group: "Startups & Internet Business" },
  { value: "digital_products", label: "Digital Products", group: "Startups & Internet Business" },
  { value: "subscription_services", label: "Subscription Services", group: "Startups & Internet Business" },
  { value: "on_demand_services", label: "On-Demand Services", group: "Startups & Internet Business" },
  { value: "social_media_platform", label: "Social Media Platform", group: "Startups & Internet Business" },
  { value: "content_platform", label: "Content Platform", group: "Startups & Internet Business" },
  { value: "creator_economy", label: "Creator Economy", group: "Startups & Internet Business" },
  { value: "edtech", label: "EdTech", group: "Startups & Internet Business" },
  { value: "healthtech", label: "HealthTech", group: "Startups & Internet Business" },
  { value: "proptech", label: "PropTech", group: "Startups & Internet Business" },
  { value: "agtech", label: "AgTech", group: "Startups & Internet Business" },
  { value: "blockchain_crypto", label: "Blockchain & Crypto", group: "Startups & Internet Business" },
  { value: "ai_ml_services", label: "AI & ML Services", group: "Startups & Internet Business" },
  { value: "cybersecurity", label: "Cybersecurity", group: "Startups & Internet Business" },
  { value: "devtools", label: "Developer Tools", group: "Startups & Internet Business" },
  { value: "no_code_low_code", label: "No-Code/Low-Code", group: "Startups & Internet Business" },
  { value: "automation_tools", label: "Automation Tools", group: "Startups & Internet Business" },
  { value: "productivity_software", label: "Productivity Software", group: "Startups & Internet Business" },
  { value: "collaboration_tools", label: "Collaboration Tools", group: "Startups & Internet Business" },
  { value: "crm_software", label: "CRM Software", group: "Startups & Internet Business" },
  { value: "hr_software", label: "HR Software", group: "Startups & Internet Business" },
  { value: "accounting_software", label: "Accounting Software", group: "Startups & Internet Business" },
  { value: "project_management", label: "Project Management", group: "Startups & Internet Business" },

  // �💡 Other
  { value: "other", label: "Other", group: "Other" }
]

export const COUNTRY_NAME_MAP: Record<string, string> = {
  'gh': 'Ghana',
  'ke': 'Kenya',
  'ng': 'Nigeria',
  'za': 'South Africa',
  'sn': 'Senegal',
  'ug': 'Uganda',
  'tz': 'Tanzania',
  'rw': 'Rwanda',
  'et': 'Ethiopia',
  'eg': 'Egypt',
  'ma': 'Morocco',
  'tn': 'Tunisia',
  'dz': 'Algeria',
  'ly': 'Libya',
  'sd': 'Sudan',
  'cm': 'Cameroon',
  'ci': 'Ivory Coast',
  'bf': 'Burkina Faso',
  'ml': 'Mali',
  'ne': 'Niger',
  'td': 'Chad'
}
